apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-watcher.name" . }}-config
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
data:
  komodor-k8s-watcher.yaml: |
{{- $daemonEnabledValues := dict "daemon" (dict "enabled" .Values.metrics.enabled) }}
{{- mergeOverwrite .Values.watcher $daemonEnabledValues  | toYaml | nindent 4 }}