apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-watcher.name" . }}-config
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
data:
  komodor-k8s-watcher.yaml: |
{{- include "watcher.values" . | nindent 4 }}
    clusterName: {{ .Values.clusterName | required "Clustername is rquired" }}