apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    app: komodor
  name: komodor-critical-pods
  namespace: komodor
spec:
  hard:
    pods: 2
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values:
          - k8s-watcher-agent-high-priority
---
