{{- if ( and (.Values.metrics).enabled .Values.daemon ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-watcher.name" . }}-daemon-config
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
data:
  telegraf.conf: |
    [global_tags]
      account_id = "${ACCOUNT_ID}"
      cluster_name = "${CLUSTER_NAME}"

    [agent]
      interval = "${INTERVAL}"
      flush_interval = "${FLUSH_INTERVAL}"

    [[outputs.http]]
      url = "{{ include "daemon.serverHost" . }}/metrics-collector/api/v1/collect"
      timeout = "${OUTPUT_TIMEOUT}"
      content_encoding = "gzip"
      {{- if .Values.proxy.https }}
      http_proxy_url = "${KOMOKW_HTTPS_PROXY_URL}"
      {{- else if .Values.proxy.http }}
      http_proxy_url = "${KOMOKW_HTTP_PROXY_URL}"
      {{- end }}
      [outputs.http.headers]
        X-ACCOUNT-ID = "${ACCOUNT_ID}"

    [[inputs.kubernetes]]
      url = "https://$NODE_NAME:10250"
      bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
      insecure_skip_verify = true
      fieldpass = ["memory_usage_bytes","cpu_usage_nanocores"]
      namedrop = ["kubernetes_system_container"]
      [inputs.kubernetes.tags]
        measure_type = "usage"

    [[inputs.kube_inventory]]
      interval = "${INTERVAL_INVENTORY}"
      ## URL for the Kubernetes API
      url = "https://kubernetes.default.svc.cluster.local"
      namespace = ""
      bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
      insecure_skip_verify = true
      resource_include = [ "pods", "nodes" ]
      response_timeout = "${INTERVAL}"
      fieldpass = ["resource_requests_millicpu_units","resource_limits_millicpu_units","resource_requests_memory_bytes","resource_limits_memory_bytes", "capacity_cpu_cores", "capacity_millicpu_cores", "capacity_memory_bytes"]
      [inputs.kube_inventory.tagpass]
        node_name=["${NODE_NAME}"]
      [inputs.kube_inventory.tags]
        measure_type = "inventory"
{{- end }}
