apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-mapper-YOUR_CLUSTER_NAME
rules:
  - apiGroups:
      - ''
    resources:
      - 'endpoints'
      - 'pods'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'apps'
    resources:
      - 'deployments'
      - 'daemonsets'
      - 'replicasets'
      - 'statefulsets'
    verbs:
      - 'get'


  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
---
