apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-watcher-daemon-config
  namespace: komodor
data:
  telegraf.conf: |
    [global_tags]
      account_id = "${ACCOUNT_ID}"
      cluster_name = "${CLUSTER_NAME}"

    [agent]
      interval = "${INTERVAL}"
      flush_interval = "${FLUSH_INTERVAL}"

    [[outputs.http]]
      url = "https://app.komodor.com/metrics-collector/api/v1/collect"
      timeout = "${OUTPUT_TIMEOUT}"
      content_encoding = "gzip"
      [outputs.http.headers]
        X-ACCOUNT-ID = "${ACCOUNT_ID}"

    [[inputs.kubernetes]]
      url = "https://$NODE_NAME:10250"
      bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
      insecure_skip_verify = true
      fieldpass = ["memory_usage_bytes","cpu_usage_nanocores"]
      namedrop = ["kubernetes_system_container"]
      [inputs.kubernetes.tags]
        measure_type = "usage"

    [[inputs.kube_inventory]]
      interval = "${INTERVAL_INVENTORY}"
      ## URL for the Kubernetes API
      url = "https://kubernetes.default.svc.cluster.local"
      namespace = ""
      bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
      insecure_skip_verify = true
      resource_include = [ "pods", "nodes" ]
      response_timeout = "${INTERVAL}"
      fieldpass = ["resource_requests_millicpu_units","resource_limits_millicpu_units","resource_requests_memory_bytes","resource_limits_memory_bytes", "capacity_cpu_cores", "capacity_millicpu_cores", "capacity_memory_bytes"]
      [inputs.kube_inventory.tagpass]
        node_name=["${NODE_NAME}"]
      [inputs.kube_inventory.tags]
        measure_type = "inventory"
---
